### ISSUE TITLE
Configuration issues and repro step questions

### ISSUE THREAD

**Issue by brettdh** [pedro-lb/expo-36-react-native-music-control#1]
1. I don't see `react-native run-ios` or `react-native run-android` anywhere in your repro steps; you are doing that, right? Not still trying to run the Expo app on the simulator and refer to native modules that don't exist in Expo? 
1. Is the error screenshot from iOS or Android?
1. Your Podfile is missing this line:
   ```
   use_native_modules!
   ```
   It belongs inside your main `target`, like [this example from the app I linked before](https://github.com/theliturgists/app/pull/214/commits/25b452f5961bb207226860275046a02ecf0808ae#diff-2505890afb91c875be64ad195a1502a6R33).

**Comment by pedro-lb** [comment]
Thanks @brettdh!

This problem and the screenshot are on Android.

I was using `expo start` before, since when running `react-native run-android` the app immediately force-closes. This also happens with a fresh new expo ejected project (right after ejecting).

**Comment by pedro-lb** [comment]
My bad, according to [this issue](https://stackoverflow.com/questions/50294874/react-native-app-with-expokit-crash-on-android-release-build) you have to run `expo start` and then `react-native run-android`, since the expo packager needs to be running.

After doing that, it finally (!) worked. Here's a screenshot of the android app:

![image](https://user-images.githubusercontent.com/22061051/72093224-bd711280-32f2-11ea-9315-f661e102f67b.png)

Thank you, @brettdh !

**Comment by brettdh** [comment]
Yep, and that’s the same for `run-ios` - the packager has to be running first.

Your Android setup looked good at a glance; glad it’s working for you. Your iOS setup should work as well with that one-line addition to your Podfile.

**Comment by brettdh** [comment]
Amending a bit: I’ve noticed that `run-android` will start a packager in a separate window, whereas `run-ios` doesn’t. This struck me as weird, and I don’t know if you’ve seen that as well; I just work around it via npm scripts.

**Comment by brettdh** [comment]
That is, `run-android` starts a packager and then kicks off a build with `gradlew`. I have a `yarn android` script that just does the build.

**Comment by pedro-lb** [comment]
> Amending a bit: I’ve noticed that `run-android` will start a packager in a separate window, whereas `run-ios` doesn’t. This struck me as weird, and I don’t know if you’ve seen that as well; I just work around it via npm scripts.

The same is happening here too! At first I simply ignored the packager, but I've fixed it with a script too. =)

**Comment by abdes-zakari** [comment]
I have the same problem, what i can make to solve this problem ?
this my package.json:

```
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "android-apk": "react-native run-android --variant=release",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "postinstall": "jetify"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "expo": "~36.0.0",
    "expo-av": "^8.0.0",
    "expo-font": "~8.0.0",
    "native-base": "^2.13.8",
    "react": "16.8.3",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-gesture-handler": "~1.4.1",
    "react-native-grid-list": "^1.1.0",
    "react-native-music-control": "^0.10.8",
    "react-native-reanimated": "~1.3.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-sound": "^0.11.0",
    "react-native-unimodules": "0.6.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-jest": "24.9.0",
    "babel-preset-expo": "~8.0.0",
    "jest": "24.9.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "private": true
}

```

**Comment by pedro-lb** [comment]
Hey @abdes-zakari !

First try to follow @brettdh steps as mentioned [here](https://github.com/expo/expo/issues/6230#issuecomment-570755617).

Note that you need to run `expo start` and then `react-native run-[android/ios]` to make the app work. If you run it with `expo start` and open it via expo it won't work.

I recommend doing that in a fresh ejected expo app in order to first learn it. On my actual app, I had to make more changes (such as upgrading deprecated libs) so it was a little more complicated.

If you have any problems let me know.

**Comment by pedro-lb** [comment]
Closing this for now, if anyone needs help comment here or feel free to open a new issue in this repo.
